import { connect } from 'react-redux';
import * as actions from '../../actions';
import VisibleTodoList from './VisibleTodoList.js';
import { getVisibleTodos, getErrorMessage, getIsFetching } from '../../reducers';

const mapStateToProps = (state, ownProps) => ({
  todos: getVisibleTodos(state, state.visibilityFilter),
  isFetching: getIsFetching(state, state.visibilityFilter),
  errorMessage:  getErrorMessage(state, state.visibilityFilter),
  filter: state.visibilityFilter
});

const mapDispatchToProps = (dispatch) => ({
  onTodoClick(id) {
    dispatch(toggleTodo(id));
  }
});

// Container generated by Connect subscribes to the store
// and passes the props to the VisibleTodoList component
export default connect(
  mapStateToProps,
  // mapDispatchToProps
  // Shorthand for mapDispatchToProps, if the parameters passed to 
  // dispatch function is same as arguments recieved
  // { onTodoClick : toggleTodo, receiveTodos }
  // Alternatively
  actions
)(VisibleTodoList);